Edit institution form
EQAR/deqar_frontend pull request #33
Opened 2019-07-15 20:25 UTC by gygabor

2019-08-05 21:23 UTC, JoshBone requested changes

2019-08-05 21:23 UTC, JoshBone commented on src/views/InstitutionForm/components/InfoBox.js
> +                  formIndex={flagIndex}s
ott van egy `s` ami nem lesz jó.

2019-08-05 21:23 UTC, JoshBone commented on package.json
> +    "react-scroll": "^1.7.12",
Ez amúgy mi ez a react-scroll? :)

2019-08-05 21:23 UTC, JoshBone commented on src/components/FormFields/FormSimpleSelect.js
> +const FormSimpleSelect = asField(({ fieldState, fieldApi, ...props }) => {
Mi a különbség a FormSelectField és a FormSimpleSelect között?

2019-08-05 22:47 UTC, gygabor commented on package.json
> +    "react-scroll": "^1.7.12",
Ha validalasnal error van, akkor odascrolloz. Idegesito volt, hogy submit utan nem latszott semmi, ha a form tetejen volt error

2019-08-06 21:10 UTC, gygabor commented on src/components/FormFields/FormSimpleSelect.js
> +const FormSimpleSelect = asField(({ fieldState, fieldApi, ...props }) => {
huh, de regen volt. Mindjart kitalalom :)

2019-08-14 07:25 UTC, gygabor commented on src/components/FormFields/FormSimpleSelect.js
> +const FormSimpleSelect = asField(({ fieldState, fieldApi, ...props }) => {
a valuekkal volt valami. kicsit atirtam most a FormSelectFieldet es igy mar tenyleg nem lesz szukseg a masikra. A kovetkezo requesben benne lesz

2019-08-16 22:58 UTC, closed without merging